pipeline{
    agent any

    stages{
        stage('Unit Tests - Backend'){
            agent{
                docker {
                    image 'golang:1.20'
                    reuseNode true
                }
            }
            environment {
                GOPATH  = "${WORKSPACE}/.go"
                GOCACHE = "${WORKSPACE}/.cache"
            }
            steps{
                dir('bugtracker-backend'){
                    sh 'go test -v ./...'
                }
            }
        }
    }
}