pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'golang:1.20'
                    reuseNode true
                }
            }
            environment {
                GOPATH  = "${WORKSPACE}/.go"
                GOCACHE = "${WORKSPACE}/.cache"
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./... 2>&1 | go-junit-report > test-results.xml'
                }
            }
            post {
                always {
                    junit 'bugtracker-backend/test-results.xml'
                }
            }
        }

        stage('Unit Tests - Frontend') {
            agent {
                docker {
                    image 'node:20'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh '''
                        npm ci
                        npm test
                    '''
                }
            }
            post {
                always {
                    junit 'bugtracker-frontend/test-results.xml'
                }
            }
        }
    }
}